# Based on the esphome configs from clydebarrow at https://gist.github.com/clydebarrow/ef89e9a93bd44771483b9144ae9042a1

substitutions:
  name: sensecap-indicator
  friendly_name: SenseCap Indicator

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio
    build_unflags: -Werror=all

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf
    # Required to achieve sufficient PSRAM bandwidth for screen graphics
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: y
      CONFIG_ESP32S3_DATA_CACHE_64KB: y
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: y
      CONFIG_SPIRAM_RODATA: y

external_components:
  - source:
      type: git
      url: https://github.com/tobi1449/esphome-sensecap-indicator-sensors.git
      ref: main
    components: [sensecap_indicator_sensors]
    refresh: 1s

# Enable Home Assistant API
api:
  encryption:
    key: !secret sensecap-indicator_api_key

# Allow Over-The-Air updates
ota:
- platform: esphome
  password: !secret sensecap-indicator_ota_password

uart:
  tx_pin: 19
  rx_pin: 20
  baud_rate: 115200

sensor:
  - platform: sensecap_indicator_sensors
    co2:
      name: "CO2 (SCD41)"
    altitude: 405
    tvoc:
      name: "TVOC (SGP40)"
    temperature:
      name: "Temperature External (AHT41)"
    temperature_internal:
      name: "Temperature Internal (SCD41)"
    humidity:
      name: "Humidity External (AHT41)"
    humidity_internal:
      name: "Humidity Internal (SCD41)"

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
  ap: {}
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/firmware/esphome-web/esp32s3.yaml@main
  import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# To have a "next url" for improv serial
web_server:

psram:
  mode: octal
  speed: 80MHz

logger:
  level: DEBUG
  hardware_uart: UART0

output:
  - platform: ledc
    pin:
      number: GPIO45
      ignore_strapping_warning: true
    id: ledc_gpio4
    frequency: 100Hz

light:
  - platform: monochromatic
    output: ledc_gpio4
    name: Display Backlight
    id: display_backlight
    restore_mode: ALWAYS_ON

spi:
  - id: lcd_spi
    clk_pin: 41
    mosi_pin: 48

i2c:
  sda: 39
  scl: 40
  scan: false
  id: bus_a

# I/O expander. Touchscreen RESET and INTERRUPT are not used.
pca9554:
  - id: p_c_a
    pin_count: 16
    address: 0x20

touchscreen:
  - platform: ft5x06
    id: ft5x06_touchscreen
    transform:
      mirror_x: true
      mirror_y: true
    on_release:
      then:
        - if:
            condition: lvgl.is_paused
            then:
              - light.turn_on: display_backlight
              - lvgl.resume:
              - lvgl.widget.redraw:

display:
  - platform: st7701s
    auto_clear_enabled: false
    update_interval: never
    spi_mode: MODE3
    color_order: RGB
    dimensions:
      width: 480
      height: 480
    invert_colors: true
    transform:
      mirror_x: true
      mirror_y: true
    cs_pin:
      pca9554: p_c_a
      number: 4
    reset_pin:
      pca9554: p_c_a
      number: 5
    de_pin: 18
    hsync_pin: 16
    vsync_pin: 17
    pclk_pin: 21
# Init sequence can be one of the defaults and/or custom sequences.
    init_sequence:
      - 1 # select canned init sequence number 1
# Custom sequences are an array, first byte is command, the rest are data.
      - [ 0xE0, 0x1F ]  # Set sunlight readable enhancement
    data_pins:
      red:
        - 4         #r1
        - 3         #r2
        - 2         #r3
        - 1         #r4
        - 0         #r5
      green:
        - 10        #g0
        - 9         #g1
        - 8         #g2
        - 7         #g3
        - 6         #g4
        - 5         #g5
      blue:
        - 15        #b1
        - 14        #b2
        - 13        #b3
        - 12        #b4
        - 11        #b5

lvgl:
  touchscreens: ft5x06_touchscreen
  buffer_size: 100%
  default_font: montserrat_48
  on_idle:
    - timeout: 15s
      then:
        - logger.log: idle 15s timeout
        - lvgl.pause:
        - light.turn_off:
            id: display_backlight
            transition_length: 5s